
# Premium Notes on NumPy


Introduction:: 
it is a fundamental package for scientific computation in python.

In [2]:
import numpy as np

mat = np.arange(9)
np.dtype('int64')
mat = mat.reshape(3,3)


print(mat)
print(mat.ndim)
print(mat.dtype)


cmp = np.array([1+2.j,2,4], dtype=complex)
print(cmp)


from numpy import pi
print(pi)

print(np.sin(90))

print(np.linspace(1,10,12))



[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
int32
[1.+2.j 2.+0.j 4.+0.j]
3.141592653589793
0.8939966636005579
[ 1.          1.81818182  2.63636364  3.45454545  4.27272727  5.09090909
  5.90909091  6.72727273  7.54545455  8.36363636  9.18181818 10.        ]


In [4]:
np.zeros_like([1,2,4])
print(np.empty(5, np.int16))

rng = np.random.default_rng()

print(rng.random())
1* rng.random((3, 2)) +10
print(np.fromfile('array.npy'))

[0 0 0 0 0]
0.44050815122600884
[1.87585069e-309 1.17119999e+171 3.21613038e-056 8.44740097e+252
 2.65141232e+180 9.92152605e+247 2.16209968e+233 2.34584010e-110
 6.01347003e-154 6.01347002e-154 6.01347002e-154 6.01347002e-154
 6.01347002e-154 6.01347002e-154 6.01347002e-154 6.55490914e-260
 4.24399158e-314 8.48798317e-314]
