In this day we learn about libraries in python, eg: NumPy , Pandas. on top of that we learn basic concept of Ai Ml and DL.

Introduction to NumPy

NumpY is a open source python library for numerical and scientific calculation.It is used in matheamatical , scientific and engineering computation.

In [45]:
#installation: 
#pip install numpy

In [4]:
import numpy as np  # as keyword is used to make a alias of variable .

In [6]:
#create a array
array = np.array([1,2,3]) 

"""
use array method to create array, here it has following parameter.
value,
dtype
"""

'\nuse array method to create array, here it has following parameter.\nvalue,\ndtype\n\n\n'

In [8]:
# lets check the type of array.
type(array)
#ndarray means, n dimensional array

numpy.ndarray

In [44]:
#some function::
# arange
rangeArr = np.arange(10) 
# reshape
reshapedArr = rangeArr.reshape(5,2)
#zeros 
zeroArr = np.zeros(100) #it takes size of array and elemnt is zero.
likeZerosArr = np.zeros_like([2,3,4,5])  #same as zeros but it takes shape/prototype of arrray.
onesArr = np.ones(10) #it takes size of array and element is one.
likeOnes = np.ones_like([[1,2,4],[4,5,6],[23,4,5]]) #smae as ones but it takes prototype of array instead size.
emptyArr = np.empty(100)


array([1.32516199e-311+1.32516073e-311j, 6.95329031e-310+1.32516073e-311j,
       1.32516073e-311+1.32516199e-311j, 1.32513470e-311+6.95329031e-310j,
       1.32515667e-311+1.32513912e-311j, 6.95329031e-310+1.32515668e-311j,
       6.95329031e-310+6.95329031e-310j, 6.95329031e-310+6.95329031e-310j,
       1.32513470e-311+1.32513470e-311j, 1.32513470e-311+1.32513912e-311j,
       1.32513470e-311+1.32515668e-311j, 1.32516073e-311+6.95329031e-310j,
       1.32516073e-311+1.32516073e-311j, 1.32515668e-311+1.32516073e-311j,
       6.95329031e-310+1.32515667e-311j, 1.32513912e-311+6.95329031e-310j,
       6.95329031e-310+6.95329031e-310j, 6.95329031e-310+6.95329031e-310j,
       6.95329031e-310+6.95329031e-310j, 6.95329031e-310+6.95329031e-310j,
       6.95329031e-310+1.32516073e-311j, 1.32516073e-311+1.32516073e-311j,
       1.32513912e-311+1.32516073e-311j, 1.32516171e-311+1.32516777e-311j,
       6.95329031e-310+1.32516777e-311j, 1.32516777e-311+1.32516171e-311j,
       1.32513470e-311+6.

In [19]:
# some properties of array in numpy.
reshapedArr.shape #provides shape(row,col) for 2-D (x,y,z) for 3-d and so on.
reshapedArr.ndim #it provides dimension 2-D , 3-D and so on.
reshapedArr.size 
# it provides no of total element in array.the size
# is equal to the multiplication of all parameter in output of shape, like in 2-D size = rows*col.

10

In [75]:
import numpy as np

# Create a 2D array
x = np.array([[10, 2, 30],
              [4, 5, 6]])
print(x)

# Casting with 'C' order (row-major)
y_c = x.astype(int, order='C')
print("C order:\n", y_c)

# Casting with 'F' order (column-major)
y_f = x.astype(int, order='F')
print("F order:\n", y_f)

atLeast_1d = np.atleast_3d(y_f)
atLeast_1d[0][0][0]
conc = np.concatenate((x,y_c,y_f), axis=1)


conc.shape
th = conc.reshape(2,3,3)
th

[[10  2 30]
 [ 4  5  6]]
C order:
 [[10  2 30]
 [ 4  5  6]]
F order:
 [[10  2 30]
 [ 4  5  6]]


array([[[10,  2, 30],
        [10,  2, 30],
        [10,  2, 30]],

       [[ 4,  5,  6],
        [ 4,  5,  6],
        [ 4,  5,  6]]])

In [84]:
import pandas as pd

df= pd.DataFrame(y_f, columns=['a','b','c'])
for col in df.columns:
    print(df[col])

0    10
1     4
Name: a, dtype: int32
0    2
1    5
Name: b, dtype: int32
0    30
1     6
Name: c, dtype: int32
