In [1]:
!pip install numpy

In [2]:
import numpy as np
print(np)

<module 'numpy' from 'C:\\Users\\DEEPAK OLI\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>


In [3]:
import numpy as np

# Creating a NumPy array from a list
arr = np.array([1, 2, 3, 4, 5])
"""
Description:
- This line creates a NumPy array from a Python list.
Parameters:
- [1, 2, 3, 4, 5]: List containing elements of the array.
Process:
- The np.array() function creates a NumPy array from the provided list.
Returned Value:
- arr: NumPy array containing elements [1, 2, 3, 4, 5].
"""

# Creating a NumPy array with specified range
arr_range = np.arange(1, 6)
"""
Description:
- This line creates a NumPy array with elements within a specified range.
Parameters:
- 1: Start of the range (inclusive).
- 6: End of the range (exclusive).
Process:
- The np.arange() function creates a NumPy array with elements from 1 to 5.
Returned Value:
- arr_range: NumPy array containing elements [1, 2, 3, 4, 5].
"""

# Reshaping a NumPy array
arr_reshaped = arr_range.reshape(5, 1)
"""
Description:
- This line reshapes a NumPy array into a different shape.
Parameters:
- 5: Number of rows.
- 1: Number of columns.
Process:
- The reshape() method reshapes the array into a 5x1 matrix.
Returned Value:
- arr_reshaped: NumPy array reshaped into a 5x1 matrix.
"""

# Transposing a NumPy array
arr_transposed = arr_reshaped.T
"""
Description:
- This line transposes a NumPy array.
Parameters:
- None.
Process:
- The T attribute transposes the array, swapping rows and columns.
Returned Value:
- arr_transposed: Transposed NumPy array.
"""

# Performing element-wise operations
arr_squared = arr_range ** 2
"""
Description:
- This line performs element-wise squaring of a NumPy array.
Parameters:
- None.
Process:
- The ** operator squares each element of the array.
Returned Value:
- arr_squared: NumPy array with elements squared.
"""

# Calculating the sum of elements
arr_sum = np.sum(arr_range)
"""
Description:
- This line calculates the sum of elements in a NumPy array.
Parameters:
- None.
Process:
- The np.sum() function computes the sum of all elements in the array.
Returned Value:
- arr_sum: Sum of elements in the NumPy array.
"""

# Finding the maximum value
arr_max = np.max(arr_range)
"""
Description:
- This line finds the maximum value in a NumPy array.
Parameters:
- None.
Process:
- The np.max() function finds the maximum value in the array.
Returned Value:
- arr_max: Maximum value in the NumPy array.
"""

# Finding the index of the maximum value
arr_argmax = np.argmax(arr_range)
"""
Description:
- This line finds the index of the maximum value in a NumPy array.
Parameters:
- None.
Process:
- The np.argmax() function finds the index of the maximum value in the array.
Returned Value:
- arr_argmax: Index of the maximum value in the NumPy array.
"""

# Slicing a NumPy array
arr_slice = arr_range[2:4]
"""
Description:
- This line slices a portion of a NumPy array.
Parameters:
- 2: Start index (inclusive).
- 4: End index (exclusive).
Process:
- Slicing selects elements from index 2 up to index 4 (excluding index 4).
Returned Value:
- arr_slice: Sliced portion of the NumPy array.
"""


'\nDescription:\n- This line slices a portion of a NumPy array.\nParameters:\n- 2: Start index (inclusive).\n- 4: End index (exclusive).\nProcess:\n- Slicing selects elements from index 2 up to index 4 (excluding index 4).\nReturned Value:\n- arr_slice: Sliced portion of the NumPy array.\n'

In [4]:
np1 = np.array([1,3])



np2 = np.array([[1,2,3],[1,2,3]])
for i in range(len(np2)):
    for j in range(len(np2[0])):
        print(np2[i][j])
    


1
2
3
1
2
3


In [5]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [6]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [5]:
import numpy as np
print(
np.empty((3,3), dtype=int, order='C'))



[[-339132808      32767  665042640]
 [       654  665043360        654]
 [ 665040320        654 1935764768]]


In [8]:
print(np.arange(10
              ))

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(np.arange(2,100,6))
type(np.array([1]))


[ 2  8 14 20 26 32 38 44 50 56 62 68 74 80 86 92 98]


numpy.ndarray

In [1]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Reshape arrays into 2D arrays with one row each
# array1_2d = np.expand_dims(array1, axis=0)
# array2_2d = np.expand_dims(array2, axis=0)

# Concatenate along axis 0 (rows)
result = np.concatenate((array1, array2_2d))

print(result)


NameError: name 'array1_2d' is not defined

In [30]:
np2 = np.array([
                [[1,2,3],[2,3,4],[6,7,8]],
                [[1,2,3],[1,2,4],[1,24,3]]
              ]
            )

print(np2.ndim)
print(np2.size)
print(np2.shape)    
print(np2.reshape(3,6 ))

3
18
(2, 3, 3)
[[ 1  2  3  2  3  4]
 [ 6  7  8  1  2  3]
 [ 1  2  4  1 24  3]]


In [ ]:
#creating an array
arr = np.array([1,2,3,4,4])
np.save("array" , arr)
loaded=np.load("array.npy")
print(loaded)





In [ ]:
#insall pandas library
#

#save it as csvp :: pd.to_csv("filename.csv")
#read csv :: pd.read_csv("filename")

In [ ]:
!pip install pandas

In [12]:
import pandas as pd
arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(arr)
print(df)

   0  1  2
0  1  2  3
1  4  5  6


In [13]:
df.to_csv("data1.csv")

In [17]:
read = pd.read_csv('data.csv')
newDf = pd.DataFrame(read)
newDf






Name  Age
0      Alice   25
1        Bob   30
2    Charlie   35
3      David   40
4       Emma   28
5      Frank   45
6      Grace   33
7      Henry   50
8   Isabella   27
9       Jack   32
10      Kate   39
11      Liam   42
12       Mia   29
13    Nathan   38
14    Olivia   31
15     Peter   36
16     Quinn   43
17    Rachel   26
18    Samuel   37